spring:
  datasource:
    url: ${MSSQL_URL:jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=DEMO_SECURITY;sendTimeAsDatetime=true;useUnicode=true;characterEncoding=UTF-8}
    username: ${MSSQL_USERNAME:sa}
    password: ${MSSQL_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update