# api:
#   version: v1
# spring:
#   datasource:
#     url: ${MSSQL_URL:jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=DEMO_SECURITY;sendTimeAsDatetime=true;useUnicode=true;characterEncoding=UTF-8}
#     username: ${MSSQL_USERNAME:sa}
#     password: ${MSSQL_PASSWORD:123456}
#   jpa:
#     show-sql: true
#     hibernate:
#       naming:
#         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#       ddl-auto: update
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: ${EMAIL_USERNAME:linhptkph30303@fpt.edu.vn}
#     password: ${EMAIL_PASSWORD:lijmkiwqcalnoyxd}
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
# cloudinary:
#   cloud-name: ${CLOUDINARY_CLOUD_NAME:DUMMY_VALUE}
#   api-secret: ${CLOUDINARY_API_SECRET:DUMMY_VALUE}
#   api-key: ${CLOUDINARY_API_KEY:DUMMY_VALUE}